version: '3.8'
services:
  spatialvid:
    # Use the GPU-enabled Dockerfile by default. Change to 'Dockerfile' if you
    # want the CPU-only image.
    build:
      context: .
      dockerfile: Dockerfile
    image: spatialvid-gpu:latest
    # Mount the repository into the container for iterative development
    volumes:
      - ./:/workspace:cached
    working_dir: /workspace
    environment:
      # Default ffmpeg path inside the runtime image. Override if needed.
      - FFMPEG_PATH=/usr/local/bin/ffmpeg
    # Useful runtime tweaks for heavy multimedia workloads
    shm_size: 1gb
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "${FFMPEG_PATH:-/usr/local/bin/ffmpeg} -version >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    # If you want to enable GPU support with Docker Engine + NVIDIA Container Toolkit,
    # start Compose with: DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose up --build
    # and add the following to this service when using docker-compose v1.28+/Compose V2:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # Alternatively, for docker run you can use: --gpus all
